"""Pydantic models for NBA Multiverse Engine."""

from pydantic import BaseModel
from typing import Literal


class Player(BaseModel):
    id: str
    name: str
    age_2010: int
    rating_2010: int
    position: str
    contract_status_2010: str
    team_2010_before_decision: str


class PrerequisiteChoice(BaseModel):
    fork_id: str
    choice_ids: list[str] = []


class SimulationWindow(BaseModel):
    start_year: int
    end_year: int


class Choice(BaseModel):
    choice_id: str
    label: str
    team_code: str
    team_color: str
    is_real_history: bool
    pitch: str
    roster_before: list[str]
    cap_space: int
    prerequisite_choices: list[PrerequisiteChoice] = []


class DecisionEvent(BaseModel):
    event_id: str
    timestamp: str
    type: str
    title: str
    subtitle: str
    description: str
    actor: dict
    choices: list[Choice]
    context: dict
    fork_year: int = 2010
    simulation_window: SimulationWindow = SimulationWindow(start_year=2010, end_year=2014)
    prerequisite_choices: list[PrerequisiteChoice] = []


class CareerMilestone(BaseModel):
    timestamp: str
    title: str
    description: str


class PlayerCareerProfile(BaseModel):
    real_milestones: list[CareerMilestone]
    sensitive_to_james_forks: list[str] = []


class TimelineEvent(BaseModel):
    event_id: str
    timestamp: str
    title: str
    description: str
    teams_affected: list[str]
    key_players: list[str]


class RealHistory(BaseModel):
    branch_id: str
    branch_name: str
    color: str
    parent_event_id: str
    parent_choice_id: str
    events: list[TimelineEvent]


class StatChange(BaseModel):
    """A single RPG stat dimension change triggered by an event."""
    dimension: Literal[
        "championships", "legacy", "media_favor",
        "fan_reputation", "cap_health", "physical_toll",
    ]
    delta: int
    reason: str


class PlayerImpact(BaseModel):
    """Butterfly effect on a constellation star from a timeline event."""
    player_id: str
    legacy: int = 0
    ring_chance: int = 0
    media_heat: int = 0
    team_fit: int = 0
    reason: str


class PlayerCareerEvent(BaseModel):
    """Alternate-universe career milestone for a non-LeBron star."""
    player_id: str
    timestamp: str
    title: str
    description: str
    vs_real_history: str = ""


class GeneratedEvent(BaseModel):
    """A single event generated by the LLM."""
    event_id: str
    timestamp: str
    title: str
    description: str
    teams_affected: list[str]
    key_players: list[str]
    confidence: float
    player_impacts: list[PlayerImpact] = []
    player_career_events: list[PlayerCareerEvent] = []


class SocialPost(BaseModel):
    """A single AI-generated fake social media post."""
    username: str
    handle: str
    avatar_color: str
    content: str
    sentiment: Literal["angry", "excited", "sarcastic", "shocked", "hate"]


class GeneratedBranch(BaseModel):
    """A complete AI-generated alternate timeline branch."""
    branch_id: str
    branch_name: str
    parent_event_id: str
    parent_choice_id: str
    narrative_summary: str
    events: list[GeneratedEvent]
    stat_changes: list[StatChange] = []
    social_posts: list[SocialPost] = []


class SSEContainer(BaseModel):
    """Wrapper for typed SSE events."""
    event_type: Literal["timeline_event", "stat_update", "social_post", "done", "error"]
    payload: dict
